<?php

namespace ApiBundle\Entity;

use Symfony\Component\HttpFoundation\Request;
/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends \Doctrine\ORM\EntityRepository
{
    public function fileterByRequest(Request $request, $user_id)
    {
        $start   = $request->get('start', 0);
        $length    = $request->get('length', 20);
        $order_field    = $request->get('order_field', 'start_dt');
        $order_dir    = $request->get('order_dir', 'DESC');
        $search = $request->get('search', false);

        $qb = $this
            ->createQueryBuilder('trip')
            ->select(['trip.id', 'trip.start_dt', 'trip.end_dt', 'trip.end_dt', 'trip.created_dt', 'trip.destination', 'trip.departure', 'trip.description'])
            ->Join('trip.user', 'user')
            ->where('user.id = :user_id')
            ->setParameter('user_id', $user_id)
            ->orderBy('trip.'.$order_field, $order_dir)
            ->setMaxResults($length)
            ->setFirstResult($start);

        if ($search){
            $qb //'%$keyword%'
                ->andWhere('trip.destination LIKE :destination')
                ->setParameter('destination', '%'.$search.'%');
        }
        //dump($qb->getQuery()->getSQL());die;

        return $qb->getQuery()->getResult();
    }
}
